### ISSUE TITLE
Variable number of re-deals in Klondike

### ISSUE THREAD

**Issue by ssterling** [nielssp/csol#1]
In the way I learned to play Klondike, the player was able to have as many re-deals as they wanted.  (I believe this goes for Microsoft Solitaire as well.)  Perhaps there could be an option to choose the amount of re-deals allowed in a game?

**Comment by nielssp** [comment]
I did a quick survey of popular Klondike implementations, and the only one I could find with a re-deal limit was XM Solitaire. So I've just gone ahead and removed the limit. 
I might add an option for it later, but it's already possible to re-enable it simply by adding "redeal 2" to the the stock-block in the [klondike game file](https://github.com/nielssp/csol/blob/master/games/klondike).
