### ISSUE TITLE
Move by a card, not by a terminal cell (h, j, k, l)

### ISSUE THREAD

**Issue by bzbug** [nielssp/csol#4]
Feature request: change (or implement additionally as different hotkeys) h-j-k-l movement so that it would move the cursor to the next card in the given direction. For example, if the cursor is at the very bottom of the game (far from the cards) and `k` is pressed, with current behaviour the cursor would move up one cell, while I suggest to move it up many cells so that it would appear on the first card above from the current position. Same for every direction.

It would make more sense to move by cards/piles, not by cells. It's already partially implemented for piles, but even there, if you put the cursor way beyond the playing field (to the right of the rightmost pile, for example) with your mouse and then press `h`, it would move `cells_count_in_a_pile_width` cells, not necessary reaching the rightmost pile.

**Comment by nielssp** [comment]
I've added a new cursor movement mode that can be enabled by adding `smart_cursor 1` to csolrc. When it's enabled, instead of just incrementing and decrementing the x/y cursor position when pressing HJKL, the game tries to find a card or pile to move to in the chosen direction.
Could you try it out and let me know if it works the way you'd expect?

**Comment by bzbug** [comment]
1. Moving the cursor to the bottom of the current pile (`Shift`+`j`) doesn't move the cursor to the very last card at the bottom of the pile, but instead moves it to the bottom of the unknown cards (playing `spider2`). Which doesn't make sense, because you can't do much with the unknown cards when there's always an uncovered card or a few of them over the pile of unknown cards and those uncovered cards are the only ones you can operate in a pile. So this basically always requires you to press additional hotkeys to move to the cards you can actually do something with. Same goes for `Shift`+`k` hotkey, which would make more sense it it moved the cursor to the first uncovered card in the pile instead of the first unknown card which you can't even use until you uncover it.

2. Is there a way to 'remember' over which card in a pile the cursor was before it was moved to another pile? That's what I have in mind: you've got your cursor over the bottommost card of the pile 1, and that is sixth card, then you move the cursor to pile 2, but it only has five cards in it, so the bottommost card in the pile 2 would be higher on the grid, which is why the cursor automatically jumps a little higher to be over that last fifth card; but if you move the cursor back to the pile 1 (with fix cards), the cursor will not jump to where is was in the pile the last time, instead it is on the fifth card, because that's the same 'row' in the grid where the cursor has been when it was over the bottommost card of the pile 2.

I'm suggesting, if it's possible, to remember the last positions of cursor in every pile. Not just moving it automatically to the bottommost or topmost cards in the piles, but actually placing it exactly where it has been, it will also be more convenient for those countless times when you think about multiple routes for your next combination and keep in mind multiple groups of cards that are involved in those routes, switch between those groups all the time. You wouldn't have to find your position again every time, instead all you'd have need to do is to not move the cursor vertically before leaving the pile.

---

Otherwise everything seems cool :]

**Comment by bzbug** [comment]
... on second thought, maybe make the 2 suggestion optional (turned on in settings), and change the standard behaviour to not ever change vertical position of the cursor when the user moves between piles (horizontally), so that the user wouldn't feel like he's losing the cursor, not feeling where it goes every time. Like, you command it to move horizontally and you expect it to only do _that_, and if it also moves vertically when you didn't command it, you stop feeling in control of the movements.

So, in my example with two piles, after moving from the pile 1 (six cards, cursor on the bottommost) to the pile 2 (five cards, the bottommost is positioned higher on the grid than the bottommost of the pile 1), maybe it would be better to not move the cursor up to the bottommost card position (5th) by default and instead let it be positioned on the same grid row it was before jumping horizontally, so that the user wouldn't lose it.

**Comment by nielssp** [comment]
I've been experimenting a bit with some improvements to horizontal cursor movement. I decided to take inspiration from text editors where the horizontal position is maintained until explicitly changed (e.g. with left/right arrow). They usually work like this:
```
long lin|e
line
longer line
```
Pressing down arrow moves the cursor (|) to the end of the second line:
```
long line
line|
longer line
```
But pressing down arrow again moves the cursor to the same offset as it was at in line 1:
```
long line
line
longer l|ine
```
Similarly, moving the cursor back up to line 1 restores its original position. So the cursor remembers its horizontal offset until it's changed with the left/right arrow keys.

I've implemented the same thing for the cursor in csol, but instead of remembering the horizontal position, the cursor remembers its vertical position until changed with j/k. This means that pressing h followed by l will always return the cursor to its original position. I've played with it for a bit, and find it pretty intuitive to use.
What do you think?

I've also improved Shift-J and Shift-K as suggested.

**Comment by bzbug** [comment]
When the cursor is on a bottommost card of a longer pile and then it goes to a shorter pile, it seems to work, but when the cursor is on a shorter pile and then it goes to a longer pile, it may take position over covered cards (which doesn't make sense, since they are useless).

So, I'm thinking, either make the cursor automatically switch to the topmost or bottommost or last remembered position in a longer pile as well, or don't ever change positions vertically when user only requests horizontal movement.

I'm beginning to think that maybe it's best to go with the latter, because all this jumping in unexpected directions seems confusing and kind of required me to think about my movement more than about the game. For some reason the same logic that's intuitive in text editors isn't helpful here, I guess it interferes with the type of thinking you have to do in the game or something.

**Comment by nielssp** [comment]
Two changes:

1. I've changed smart_cursor so that face-down cards are now ignored (unless they can be turned). So when the cursor is moved left or right onto a face-down card, the cursor is automatically moved down to the first face-up card.
2. I've added a new setting `keep_vertical_position 1` that completely disables the automatic adjustment of the vertical cursor position when moving horizontally. This means that the cursor can move outside of the cards and it may be necessary to press j or k after moving horizontally to get to a card.

**Comment by bzbug** [comment]
1. Both options (`smart_cursor` & `keep_vertical_position`) are on.
2. Go to a bottommost card of a longer pile.
3. Switch to a shorter pile so that the cursor would still be on the bottommost card, just not at the first terminal row of that card.
4. Press `k` to jump one card higher

 -> jumps to the first row of the current card (doesn't change cards or meaningful positions).

**Expected behaviour:** jump to the previous card or to the additional stop above the pile if there's no previous uncovered card in the pile (the 'additional stop' is where the cards get stored after a group of them is finished from `K` to `A`).

At the same time `Space` works on a card even if the cursor is not at the first terminal row of that card.

---

1. `smart_cursor` is on, `keep_vertical_position` is off.
2. Select any card, go to any pile where you could place it and move it there.
3. With the cursor over the pile where you've moved the card to, press `j` to move one card lower, so that the cursor would be placed over the card you've just moved.
4. Press `u` to undo.

-> the cursor doesn't jump automatically to the first row of the bottommost card (which should be a row higher now than the current position, since the last card disappeared back to where it was taken from).

**Expected behaviour:** since we change vertical position here automatically, I'd expect the cursor to move vertially on `undo`, too.

And there's also the question about what to do after `redo`-ing. Suppose, after 4th step we got our cursor to be at the topmost row of the bottommost card in the pile (one cell higher). Should the cursor move back to the topmost row of the bottommost card after `redo`-ing (kind of like remembering where it was before the whole `undo` + `redo` cycle) or should it stay where it was? I'm thinking, in the spirit of this way of doing things (with `keep_vertical_position` off), the cursor should return to the bottommost card after `redo`-ing.

**Comment by nielssp** [comment]
Both should be fixed now.

1. The smart cursor now ignores the card it's over even when the cursor is not positioned on the top row of the card.
2. When keep_vertical_position is off, after each move (including undo, redo, and auto) the smart cursor will now attempt to adjust its vertical position in such a way that it's always over a card (i.e. move up when one or more cards are removed from the pile) and as close to its stored vertical position as possible (i.e. move down when one or more cards are added to the pile).
