### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by bzbug** [nielssp/csol#5]
1. Update `README.md` file so that it would include _all_ features. For example, I can't find hotkeys `u` (undo) and `U` (redo) there, although they work for me. I don't know what other features there are, but it would be useful to know about them.

2. Write a `man`/`info` page, so that people wouldn't need to open a browser to read the docs.

**Comment by nielssp** [comment]
I've added the missing key bindings to the README.

I'll see if I can put together a proper man page as well.

**Comment by nielssp** [comment]
Man page added.
