### ISSUE TITLE
Bug with relative searches after including

### ISSUE THREAD

**Issue by MinekPo1** [nielssp/csol#6]
Note: See [here](https://www.gitlab.com/MinekPo1/bugs/-/tree/csol-dir) for files used to recreate the bug.

If a configuration file uses the `include` command, any following `include`,
`game_dir` and `theme_dir` commands will be relative to that file, not the one executing them.

```
> csol -c conf1
Using configuration file: conf1
Warning: file "example" not found, searching all theme files
theme not found: 'example'
```

I believe this is caused by `cwd` of `execute_file` in `rc.c` being overridden when
the function is called recursively.

This may be caused by `dirname` not returning unique pointers every time or just some c jank.

**Comment by nielssp** [comment]
Thank you for reporting this. It definitely looks like `dirname` is the culprit. The way the function is described makes it a bit of a footgun:

>        Both dirname() and basename() may modify the contents of  path,  so  it
>        may be desirable to pass a copy when calling one of these functions.
> 
>        These  functions  may  return  pointers  to statically allocated memory
>        which may be overwritten by subsequent calls.  Alternatively, they  may
>        return  a  pointer to some part of path, so that the string referred to
>        by path should not be modified or freed until the pointer  returned  by
>        the function is no longer required.

It should be fixed now in master.
