### ISSUE TITLE
Redealing after won game causes terminal cursor to appear

### ISSUE THREAD

**Issue by mery6299** [nielssp/csol#7]
Like in title, after winning a game I noticed that there is an extra block cursor as seen on picture. 
Happens for me in spider(1,2) and freecell. I use foot terminal emulator. 
Not sure what info would be useful.

![20230217_14h38m17s_grim](https://user-images.githubusercontent.com/77493293/219682999-0f254bb2-69d5-4ae8-8b9d-03cf0be5e0a9.png)

**Comment by nielssp** [comment]
Thank you for reporting this, it should be fixed in master.
