### ISSUE TITLE
Hint to press enter in quit prompt

### ISSUE THREAD

**Issue by MindfulMinun** [nielssp/csol#8]
When the player presses Q, this prompt appears:

![](https://github.com/nielssp/csol/assets/15158256/fc79ccd5-88c6-4d56-bd4d-ddee31e56fb9)

The player can then make a selection with Y or N as shown in the prompt, but I've also noticed that you can press Enter to continue the game. Generally the capitalized letter in a terminal prompt means it's the default.

Consider changing the prompt to `Quit? (y/N)` (with a lowercase "y") to hint to the user that the the default option will be to continue the game, and can also be triggered by pressing Enter.

**Comment by nielssp** [comment]
Good point, I've made the 'Y' lowercase.

**Comment by MindfulMinun** [comment]
Thank you!
